### ISSUE TITLE
Unable to download file on browser

### ISSUE THREAD

**Issue by navpret** [imneonizer/autolycus#30]
When adding magnet links to the `add torrent` bar, the torrent is accepted and downloaded, the file even gets saved in the downloads' folder on the server. 

But when clicking the menu to locally download it, it does not respond. Checking the network logs, it does not even send a download request (maybe because I configured it improperly because there's no guide). This issue makes the application completely unusable. 

Thanks

**Comment by imneonizer** [comment]
Yes, the drop-down menu does show the download option but sadly I haven't implemented downloading the root directory as it needs to be archived first as my primary focus was to download or stream individual files.

What you can do is go inside the directory and then click on a file to download, it should work.
If it's a video file you can even click on it to play directly inside the application (beware it will increase the memory consumption).
