### ISSUE TITLE
VPN Docker Combination

### ISSUE THREAD

**Issue by balupton** [imneonizer/autolycus#33]
I'm currently using https://github.com/haugene/docker-transmission-openvpn for a seedbox, however I'm very interested in BitTorrent v2, which it seems your project supports via libtorrent. As such, it would be cool to eventually replace that docker container with one for this project.

**Comment by imneonizer** [comment]
Hey,

Can you please explain your exact requirements?
- Why do you want VPN support ?
- Does this means you want to access your seed box from outside the network via connecting to same vpn provider ?
- Or you just want to run the seedbox via VPN tunnel to have faster speed and enhanced privacy ?
- do you want to connect your own vpn provider or any vpn tunnel should work ?

Though VPN support isn't in the roadmap If it seems like a nice addition I would try to add that feature aswell.
Please don't expect fast feature development as I am the only maintainer of the project and I am not a full-stack / backend engineer.
