### ISSUE TITLE
Adding ability to updoad `.torrent` files for download and through direct download links

### ISSUE THREAD

**Issue by SnazzyCoder** [imneonizer/autolycus#39]
It would be great if the application allowed to upload `.torrent` files to autolycus, downloaded from somewhere like yts.mx, so that they could be downloaded as well (like seedr.cc does).

Also, sometimes, for example, a `.mp4` file download is available for direct downalod, but the server is too slow (~200kbps), and it's not really convinient to download it all on one's device. Could the hosting server be used as a middle man in that case, by pasting the download link for a `.mp4` file into autolycus, and finding it downloaded till tomorrow, from where it could be downloaded instantly.

These features would be great... Thank You...

**Comment by imneonizer** [comment]
There are two different features here:
- Uploading `.torrent` file instead of `Magnet`
- Ability to fetch downloadable links from anywhere on the internet.

This can be done, but it's not on high priority right now.

**Comment by SnazzyCoder** [comment]
Thanks. But I think I didn't properly explain the second one.

I meant that, for example, we have a worldfree4u (a movie downloading site) `.mkv` direct download link already, which provides the ability to download movies from their own servers, which are very slow, and it takes an eternity to download a 200mb file. Downloading it from a phone or PC results in unexpected complications, and they need to be always active, since pausing most of these downloads fails them.

The ability to paste these slow download links into autolycus, keep actively downloading them on the self-hosted instance (which would take around 1 hour even with blazing internet speeds because of speed caps on the transmission side), then logging back in to autolycus to see the file downloaded onto our server's storage, and then download it locally from there. It would be much faster and convinient after that, since there would be no caps on transfer speeds.

Does this sound like a good idea? The other most anticipated feature imo...

**Comment by Deepnerd** [comment]
can you tell me how to fix the "Our Server is Feeling a Little Down" ? how to get this work?

**Comment by Vinoddjr** [comment]
> can you tell me how to fix the "Our Server is Feeling a Little Down" ? how to get this work?

This you can resolve by modifying .env file where remove 5000 and just point to api http://server-address/api

**Comment by imneonizer** [comment]
@SnazzyCoder I am working on the core module as a separate module for the Autolycus V2, it supports torrent files as well https://github.com/imneonizer/libtorrentx
