### ISSUE TITLE
Please provide prebuilt docker image to deploy autolycus

### ISSUE THREAD

**Issue by cinetube** [imneonizer/autolycus#53]
Please provide prebuilt docker image to deploy autolycus

**Comment by imneonizer** [comment]
Docker containers are already hosted on docker hub at https://hub.docker.com/repository/docker/imneonizer/autolycus

Instructions to deploy the application, modify ports and env variables as necessary
````bash
mkdir -p autolycus
cd autolycus
wget -O docker-compose.yml "https://gist.githubusercontent.com/imneonizer/24c597460555344dbd2db075356e6004/raw/3220742473f099993bf393ba87e5fbb42b64479f/docker-compose-autolycus.yml"
docker-compose up -d
````

More info at #42
