### ISSUE TITLE
Issues - Feature request

### ISSUE THREAD

**Issue by 00itsm00** [imneonizer/autolycus#78]
Hi there,

Shout out for the work you did. 

there are few bugs if you can solve please:

1. on logout it shows errors and never gets back to login url until we clear cookies.
2. login issue (this one is already in consideration i assume)
3. downloads are not completing.
I added 6 gibs file and downloaded it on another server it never completes until unless i start the download again and again and click on download link.
4. not getting complete url while clicking on copy link. ll have to put it manually "download=true" at the end always.
5. Recyclebin doesn't work, if i delete any file it still shows the same amount of storage which got occupied after downloading the file. Seems like it doesn't deletes the file. I tried to check in download folder but i am not able to find the file there it still is showing less storage.

I set it up on Digital Ocean and got 9 to 14 mb/s

What you can add:
How much data has been downloaded
Search downloaded Files
context menu same as seedr..cc (as it only pops up by clicking on 3 dots)
Favorites

On hover it shows information like time and date alongwith torrent name and magnet super like for that.

Thank you for all the hard work, Appreciate your work really.

Regards:

itsM

**Comment by imneonizer** [comment]
This is not a production-grade finished project, and I am not updating is aswell. Although I have plans for V2 of this project.
