### ISSUE TITLE
stuck here

### ISSUE THREAD

**Issue by Dikko3506** [imneonizer/autolycus#80]
![image](https://user-images.githubusercontent.com/43563193/183572574-1c956c22-7059-4f24-9759-0da11a963aba.png)

**Comment by imneonizer** [comment]
- What's the issue? The logs say it's running on port 3000.
- Are you running the docker-compose command on your local system or in a remote shell?

**Comment by Dikko3506** [comment]
i am running docker on azure platform its stuck here but when i open vm ip its show nothing

**Comment by imneonizer** [comment]
I see there is some issue with the API, possibly `flask-sqlalchemy` module. You can use pre built docker images from docker hub.
https://hub.docker.com/r/imneonizer/autolycus
