### ISSUE TITLE
Error on pip install requirements

### ISSUE THREAD

**Issue by Xeiniac** [imneonizer/autolycus#82]
Hello I keep getting an installing the requirements using pip
https://hastebin.com/azerejamay

I'm using an Oracle Cloud Arm based VM Ubuntu 18.04

**Comment by Umer-Nazir** [comment]
Update the gevent to latest in api/requirement.txt

**Comment by imneonizer** [comment]
It's fixed in [d4508bb](https://github.com/imneonizer/autolycus/commit/d4508bb95dcb9f383093b0bfd5fce265ab84985b)
