### ISSUE TITLE
How can i fix this?

### ISSUE THREAD

**Issue by atharvavshelke** [imneonizer/autolycus#84]
api_1    |
api_1    | Error: class uri 'gevent' invalid or not found:
api_1    |
api_1    | [Traceback (most recent call last):
api_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 99, in load_class
api_1    |     mod = importlib.import_module('.'.join(components))
api_1    |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
api_1    |     return _bootstrap._gcd_import(name[level:], package, level)
api_1    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
api_1    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
api_1    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
api_1    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
api_1    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
api_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 14, in <module>
api_1    |     import gevent
api_1    |   File "/usr/local/lib/python3.7/site-packages/gevent/__init__.py", line 86, in <module>
api_1    |     from gevent._hub_local import get_hub
api_1    |   File "/usr/local/lib/python3.7/site-packages/gevent/_hub_local.py", line 101, in <module>
api_1    |     import_c_accel(globals(), 'gevent.__hub_local')
api_1    |   File "/usr/local/lib/python3.7/site-packages/gevent/_util.py", line 148, in import_c_accel
api_1    |     mod = importlib.import_module(cname)
api_1    |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
api_1    |     return _bootstrap._gcd_import(name[level:], package, level)
api_1    |   File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
api_1    | ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject
api_1    | ]
api_1    |

**Comment by imneonizer** [comment]
It's fixed now by [d4508bb](https://github.com/imneonizer/autolycus/commit/d4508bb95dcb9f383093b0bfd5fce265ab84985b)

**Comment by atharvavshelke** [comment]
thx for the fix it's working right now
