### ISSUE TITLE
Space Available Feature!

### ISSUE THREAD

**Issue by imranext** [imneonizer/autolycus#85]
Please add space informations of SSD/HDD.

**Comment by imneonizer** [comment]
It's already there, 

- Desktop View
![image](https://user-images.githubusercontent.com/13932346/209275453-34987583-2c69-4827-afd5-16b24c3222e5.png)

- Mobile View (a thin blue line at very bottom)
![image](https://user-images.githubusercontent.com/13932346/209275521-f1b57959-5952-4e8a-9193-52e97a835078.png)
